<!DOCTYPE HTML>

<html>
<head>
    <title>AutoDial</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!--[if lte IE 8]><script src="/assets/js/ie/html5shiv.js"></script><![endif]-->
    <link rel="stylesheet" href="/assets/css/main.css" />
    <!--[if lte IE 9]><link rel="stylesheet" href="/assets/css/ie9.css" /><![endif]-->
    <!--[if lte IE 8]><link rel="stylesheet" href="/assets/css/ie8.css" /><![endif]-->

    <?=$this->headLink()->setAntiCache(App_View_Helper_HeadLink::ANTI_CACHE_MTIME_GET_PARAM)?>
    <?=$this->headScript()->setAntiCache(App_View_Helper_HeadScript::ANTI_CACHE_MTIME_GET_PARAM)?>
</head>
<body>

<!-- Wrapper -->
<div id="wrapper">

    <!-- Header -->
    <header id="header">
        <h1><a href="<?= $this->url('index') ?>">AutoDial</a></h1>
        <nav class="links">
            <? if ($this->currentAdmin->exists()) : ?>
                <?= $this->render('_menu.phtml'); ?>
            <? endif; ?>
        </nav>
        <nav class="main">

        </nav>
    </header>

    <!-- Main -->
    <div id="main">
        <?= $this->layout()->content ?>
    </div>
</div>

<!-- Scripts -->
<script src="assets/js/jquery.min.js"></script>
<script src="assets/js/skel.min.js"></script>
<script src="assets/js/util.js"></script>
<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
<script src="assets/js/main.js"></script>

</body>
</html>