<ul class="menu">
    <li class="menu-item"><a href="<?= $this->url('admin_index') ?>">Администраторы</a></li>
    <li class="menu-item"><a href="<?= $this->url('dial_rule_index') ?>">Обзвоны</a></li>
    <li class="menu-item"><a href="<?= $this->url('dial_settings_index') ?>">Настройки</a></li>
    <!--
    <li class="menu-item">
        <a href="#"></a>
        <ul class="submenu">

        </ul>
    </li>-->
    <li class="menu-item"><a href="<?= $this->url('dial_log_index') ?>">Отчеты</a></li>
    <li class="menu-item"><a href="<?= $this->url('index_logout') ?>">Выход</a></li>
</ul>