<article class="post">
    <header>
        <div class="title">
            <h2><?= $this->user->getFullName() ?></h2>
        </div>
    </header>

    <form method="post" action="<?= $this->url(array('user_id' => $this->user->getId(), 'act' => 'save'), 'user_edit') ?>">
        <div class="row uniform">
            <div class="6u 12u$(xsmall)">
                Фамилия
            </div>
            <div class="6u 12u$(xsmall)">
                <? if ($this->isEdit) : ?>
                    <input type="text" name="user_surname" value="<?= $this->validateResult->getData('surname') ?>" <?= $this->validateResult->isFieldError('surname') ? 'class="verror"' : '' ?>>
                <? else : ?>
                    <?= $this->user->getSurname() ?>
                <? endif; ?>
            </div>
            <div class="6u 12u$(xsmall)">
                Имя
            </div>
            <div class="6u 12u$(xsmall)">
                <? if ($this->isEdit) : ?>
                    <input type="text" name="user_name" value="<?= $this->validateResult->getData('name') ?>" <?= $this->validateResult->isFieldError('name') ? 'class="verror"' : '' ?>>
                <? else : ?>
                    <?= $this->user->getName() ?>
                <? endif; ?>
            </div>
            <div class="6u 12u$(xsmall)">
                Отчество
            </div>
            <div class="6u 12u$(xsmall)">
                <? if ($this->isEdit) : ?>
                    <input type="text" name="user_patronymic" value="<?= $this->validateResult->getData('patronymic') ?>" <?= $this->validateResult->isFieldError('patronymic') ? 'class="verror"' : '' ?>>
                <? else : ?>
                    <?= $this->user->getPatronymic() ? $this->user->getPatronymic() : '<br>' ?>
                <? endif; ?>
            </div>
            <div class="6u 12u$(xsmall)">
                Телефон
            </div>
            <div class="6u 12u$(xsmall)">
                <? if ($this->isEdit) : ?>
                    <input type="text" name="user_phone" value="<?= $this->validateResult->getData('phone') ?>" <?= $this->validateResult->isFieldError('phone') ? 'class="verror"' : '' ?>>
                <? else : ?>
                    <?= $this->user->getPhone() ?>
                <? endif; ?>
            </div>
            <div class="6u 12u$(xsmall)">
                Адрес
            </div>
            <div class="6u 12u$(xsmall)">
                <? if ($this->isEdit) : ?>
                    <textarea name="user_full_address" <?= $this->validateResult->isFieldError('full_address') ? 'class="verror"' : '' ?>><?= $this->validateResult->getData('full_address') ?></textarea>
                <? else : ?>
                    <?= $this->user->getFullAddress() ? $this->user->getFullAddress() : '<br>' ?>
                <? endif; ?>
            </div>

            <div class="6u 12u$(xsmall)">
                Адрес электронной почты
            </div>
            <div class="6u 12u$(xsmall)">
                <? if ($this->isEdit) : ?>
                    <input type="text" name="user_email" value="<?= $this->validateResult->getData('email') ?>" <?= $this->validateResult->isFieldError('email') ? 'class="verror"' : '' ?>>
                <? else : ?>
                    <?= $this->user->getEmail() ? $this->user->getEmail() : '<br>' ?>
                <? endif; ?>
            </div>
            <div class="6u 12u$(xsmall)">
                Округ
            </div>
            <div class="6u 12u$(xsmall)">
                <? if ($this->isEdit) : ?>
                    <input type="text" name="user_district" value="<?= $this->validateResult->getData('district') ?>" <?= $this->validateResult->isFieldError('district') ? 'class="verror"' : '' ?>>
                <? else : ?>
                    <?= $this->user->getDistrict() ? $this->user->getDistrict() : '<br>' ?>
                <? endif; ?>
            </div>
            <div class="6u 12u$(xsmall)">
                Район
            </div>
            <div class="6u 12u$(xsmall)">
                <? if ($this->isEdit) : ?>
                    <input type="text" name="user_region" value="<?= $this->validateResult->getData('region') ?>" <?= $this->validateResult->isFieldError('region') ? 'class="verror"' : '' ?>>
                <? else : ?>
                    <?= $this->user->getRegion() ? $this->user->getRegion() : '<br>' ?>
                <? endif; ?>
            </div>
            <div class="6u 12u$(xsmall)">
                Идентификатор 1
            </div>
            <div class="6u 12u$(xsmall)">
                <? if ($this->isEdit) : ?>
                    <input type="text" name="user_identificator_first" value="<?= $this->validateResult->getData('identificator_first') ?>" <?= $this->validateResult->isFieldError('identificator_first') ? 'class="verror"' : '' ?>>
                <? else : ?>
                    <?= $this->user->getIdentificatorFirst() ? $this->user->getIdentificatorFirst() : '<br>' ?>
                <? endif; ?>
            </div>
            <div class="6u 12u$(xsmall)">
                Идентификатор 2
            </div>
            <div class="6u 12u$(xsmall)">
                <? if ($this->isEdit) : ?>
                    <input type="text" name="user_identificator_second" value="<?= $this->validateResult->getData('identificator_second') ?>" <?= $this->validateResult->isFieldError('identificator_second') ? 'class="verror"' : '' ?>>
                <? else : ?>
                    <?= $this->user->getIdentificatorSecond() ? $this->user->getIdentificatorSecond() : '<br>' ?>
                <? endif; ?>
            </div>
            <? if ($this->user->getIdentifictorList()) : ?>
                <div class="6u 12u$(xsmall)">
                    Дополнительные идентификаторы
                </div>
                <div class="6u 12u$(xsmall)">
                    <? foreach ($this->user->getIdentifictorList() as $identificator) : ?>
                        <?= $identificator->getIdentificator(); ?><br>
                    <? endforeach; ?>
                </div>
            <? endif; ?>
            <? if ($this->isEdit) : ?>
                <div class="12u$">
                    <input type="submit" value="Сохранить" />
                </div>
            <? endif ?>
        </div>
    </form>

    <? if (!$this->isEdit) : ?>
        <footer>

            <ul class="actions">
                <li><a href="<?= $this->url(array('user_id' => $this->user->getId(), 'act' => 'edit'), 'user_edit') ?>" class="button">Редактировать</a></li>

                <? if ($this->user->isActive()) : ?>
                    <li><a href="<?= $this->url(array('user_id' => $this->user->getId()), 'user_set_deleted') ?>" class="button">Удалить</a></li>
                <? else : ?>
                    <li><a href="<?= $this->url(array('user_id' => $this->user->getId()), 'user_set_active') ?>" class="button">Восстановить</a></li>
                <? endif; ?>
            </ul>
        </footer>
    <? endif; ?>
</article>

<article class="post">
    <header>
        <div class="title">
            <h2>Статистика по вызовам</h2>
        </div>
    </header>

    <div class="row uniform">
        <div class="6u 12u$(xsmall)">
            Количетсво вызовов
        </div>
        <div class="6u 12u$(xsmall)">
           <?= $this->callCount ?>
        </div>
        <div class="6u 12u$(xsmall)">
            Дата первого вызова
        </div>
        <div class="6u 12u$(xsmall)">
            <?= $this->firstCall ?>
        </div>
        <div class="6u 12u$(xsmall)">
            Дата последнего вызова
        </div>
        <div class="6u 12u$(xsmall)">
            <?= $this->lastCall ?>
        </div>
        <div class="6u 12u$(xsmall)">
            Статус последнего вызова
        </div>
        <div class="6u 12u$(xsmall)">
            <?
            switch ($this->lastStatus)
            {
                case 'busy': echo 'занято'; break;
                case 'answered': echo 'ответ получен'; break;
                case 'no_answered': echo 'нет ответа'; break;
                case 'failed': echo 'сброс вызова'; break;
            }
            ?>
        </div>
        <div class="6u 12u$(xsmall)">
            <a href="<?= $this->url(array('dial_log_id' => $this->lastDialLogId), 'dial_log_info') ?>"> Послений отчет</a>
        </div>
        <div class="6u 12u$(xsmall)">

        </div>
    </div>
</article>